AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]

Style/GlobalVars:
  Exclude:
    - "spec/worker_spec.rb"
    # The introduction of a dummy global variable greatly simplified
    # testing in this case, as it made reassignment between scopes much
    # more straightforward. I didn't consider that particularly harmful.
    # Thoughts?

Lint/MissingSuper:
  Exclude:
    - "/**/*"
