AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]

Lint/MissingSuper:
  Enabled: false

# Essentially, logs are making methods and blocks huge, not the
# logic itself. We thus decided to disable some linter checks
# related to number of lines.

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false